apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "python-chart2.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "python-chart2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "python-chart2.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.container.port }}
        envFrom:
        - configMapRef:
            name: "{{ .Values.configMap.name }}"