# kubectl create deployment jenkins -v JENKINS_HOME:JENKINS_HOME -v /var/run/:/var/run --image=jenkins/jenkins:lts -o yaml --dry-run=client
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  creationTimestamp: null
  namespace: jenkins
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        name: jenkins
        resources: {}
status: {}
