apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.redisService.port }}
      targetPort: {{ .Values.redisService.targetport }}
  selector:
    app: {{ .Values.redisLabel.app }}