---
apiVersion: v1
kind: Service
metadata:
  name: external-lexalyzer-service
  namespace: app-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    app: lexalyzer
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80