# - name: install and configure kubectl
#   hosts: bastion
#   roles:
#     - roles/kubectl

# - name: install docker
#   hosts: bastion
#   become: yes
#   roles:
#     - roles/docker

- name: install jenkins
  hosts: bastion
  roles:
    - roles/k8s

# helm repo add jenkins https://charts.jenkins.io
# helm repo update
# helm install jenkins jenkins/jenkins